[neovim.files]
"config/nvim" = "~/AppData/Local/nvim"

[glazewm.files]
"config/GlazeWM/config.yaml" = "~/.glzr/glazewm/config.yaml"

[datagrip.files]
"config/Data Grip/.ideavimrc" = "~/.ideavimrc"

[visualstudio.files]
"config/Visual Studio/.vimrc" = "~/.vimrc"
